### ISSUE TITLE
求问之后大佬准备将这篇论文发在哪里

### ISSUE THREAD

**Issue by shikun1408** [kexinhuang12345/scGNN#1]
因为我现在也在做图的工作，也做到了sc-rna impute的这一块，想着将图卷积和scrna-impute结合起来，结果就看到了您的论文，我之前一直以为是发表在icml了，今天才注意到是先投在了workshop，所以有了这样的疑问。谢谢，如果不方便回答也没事的。

**Comment by kexinhuang12345** [comment]
Hi, 对的，暂时应该没有计划发表，你只要cite我们就可以了。

**Comment by shikun1408** [comment]
十分感谢您的回复，谢谢，你真的很优秀！

**Comment by shikun1408** [comment]
您好，我想冒昧的问一下，请问您是否方便将这篇论文的result中的聚类的相关代码发给我看看吗，我自己在这方面的实现遇到了一些问题，从而想着向您寻求帮助，十分谢谢您，我的邮箱是759188075@qq.com  。 真的十分感谢！
